### ISSUE TITLE
Class "Db8\Module\Db8404errors\Administrator\Helper\ErrorHelper" not found

### ISSUE THREAD

**Issue by extonjaez** [pe7er/mod_db8404errors#7]
Hello

I have this error in frontend when "error 404 " module is enabaled
_Class "Db8\Module\Db8404errors\Administrator\Helper\ErrorHelper" not found_
regards

System Information
Error 404 version 2.0.0
PHP Built On	Linux s22095112 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64
Database Type	mysql
Database Version	10.2.44-MariaDB
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	8.1.9
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 4.2.3 Stable [ Uaminifu ] 27-September-2022 15:35 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by pe7er** [comment]
@extonjaez Thanks for reporting this issue. I'll look into it soon.

**Comment by pe7er** [comment]
The issue was caused by an error in the xml manifest. I've published a fixed version (Thanks @AlainRnet for the fix!)

@extonjaez you might have to uninstall the previous version and then install v2.0.1.
